PACKAGE = jquery-roles-ui

MODULES = \
	roles.aria.ui.js \
	roles.button.ui.js \
	roles.tablist.ui.js \
	roles.tree.ui.js \
	roles.dialog.ui.js

CSS_DIR = theme
CSS = \
	ui.button.css \
	ui.toolbar.css \
	ui.tree.css

include build/rules.mk

